version: "3.7"

services:
  eureka-server:
     image: mycompany/firstspringeurekaserverdiscovery:0.0.1-SNAPSHOT
     container_name: eureka_server_discovery
     environment:
       - SPRING_APPLICATION_NAME=firstspringeurekaserverdiscovery
       - SPRING_PROFILES_ACTIVE=dev
       - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
       - SPRING_CLOUD_CONFIG_TOKEN=myroot
     ports:
       - "8070:8070"
     networks:
       backend:
         aliases:
           - "eureka-server"
     depends_on:
       - config-server
     restart: on-failure

  config-server:
    image: mycompany/firstspringconfigurationserver:0.0.1-SNAPSHOT
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=native,git,vault
      - SPRING_APPLICATION_NAME=config-server
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=classpath:/config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/zakaria-shahen/firstspringconfigurationserver
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH-PATH=src/main/resources/config
      - SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST=vault
      - SPRING_CLOUD_CONFIG_SPRING_VAULT_PORT=8200
      - SPRING_CLOUD_CONFIG_SPRING_VAULT_kv-VERSION=2
      - SPRING_CLOUD_CONFIG_SPRING_VAULT_PROFILE-SEPARATOR=/
      - ENCRYPT_KEY=my-secret
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
    depends_on:
      - vault
    restart: on-failure

  vault:
    image: vault:1.12.2
    container_name: dev_vault
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      backend:
        aliases:
          - "vault"

networks:
  backend:
    driver: bridge